language:
    - python

python:
    - '3.6'
    - '3.7'

install:
    - pip install -r requirements.txt
    - pip install pyharmony
    - sudo apt-get install libxml2-utils libxml2-dev

script:
    - xmllint --noout profile/*/*.xml
    - ./write_profile.py
    - ./harmony_hub.py
